
spring:
  application:
    name: healthygation

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: ${OPENAI_BASE_URL:https://api.openai.com/v1}
  docker:
    compose:
      enabled: true
      lifecycle-management: start_only

healthygation:
    fhir:
        base-url: ${FHIR_BASE_URL:http://localhost:8085/hapi-fhir-jpaserver/fhir/}
    graph-rag:
        neo4j-uri: ${NEO4J_URI:bolt://localhost:7687}
        neo4j-username: ${NEO4J_USERNAME:neo4j}
        neo4j-password: ${NEO4J_PASSWORD:healthygation}
        embedding-dimensions: 1536
        similarity-top-k: 5
        cypher-generation-enabled: false
server:
  port: ${PORT:8083}
